
export const CLOUD_COLUMNS = {
 ID: "ID_REGISTRO",
 UNIQUE_KEY: "CLAVE_UNICA",
 ENTRY_DATE: "FECHA_INGRESO",
 DATE: "FECHA",
 ERP_ORDER: "ERP",
 BARCODE: "COD PRODUCTO",
 PRODUCT_NAME: "DESCRIPCION",
 QUANTITY: "CANTIDAD",
 EXPECTED: "STOCK_TEORICO",
 DIFF: "DIFERENCIA",
 LABEL: "ETIQUETAS",
 MONTH: "MM",
 YEAR: "YYYY",
 INCIDENT: "FRC",
 AUDIT_STATUS: "ESTADO_AUDITORIA",
 AUDIT_SCORE: "PUNTAJE_AUDITORIA",
 // Metadata para Inteligencia Colectiva
 IA_SIGNATURE: "FIRMA_IA",
 PHOTO_URL: "FOTO_ALMACENADA"
};

export const SYNC_ENGINE_VERSION = "7.1.1-AI-FIX";

// Forced GitHub sync
