
export const SHEET_COLUMNS = {
    ID: "ID_REGISTRO",
    UNIQUE_KEY: "CLAVE_UNICA",
    DATE: "FECHA",
    ERP_ORDER: "ERP",
    BARCODE: "CODIGO",
    PRODUCT_NAME: "PRODUCTO",
    QUANTITY: "CANTIDAD",
    EXPECTED: "STOCK_TEORICO",
    DIFF: "DIFERENCIA",
    LABEL: "ETIQUETAS",
    MONTH: "MM",
    YEAR: "YYYY",
    INCIDENT: "FRC",
    AUDIT_STATUS: "ESTADO_AUDITORIA",
    AUDIT_SCORE: "PUNTAJE_AUDITORIA",
    // Nueva columna para Inteligencia Colectiva
    IA_SIGNATURE: "FIRMA_IA"
};

export const SYNC_ENGINE_VERSION = "7.1.0-AI-SYNC";
